### ISSUE TITLE
ToDo CLEF scorer

### ISSUE THREAD

**Issue by aflueckiger** [impresso/CLEF-HIPE-2020-scorer#1]
**decisions**
- document-level F1-score to weight long/short docs equally, 
- treat nested entities (columns) individually
- treat every column separate; NEL & NERC & components
- no fuzziness on the type, only for the boundary (one token needs to match)
-  no macro_type in TSV

-->  compare F1-score with CONLL script as a sanity check

**programming**
- [x] implement script scaffolding
- [x] output relevant metrics as tsv
- [x] output all metrics as json
- [x] implement document-level F1 macro score with std. dev. as a stability measure
- [x] unit test for complicated cases (double hits including TP and FP)
- [x] include original numbers TP / FP / FN
- [x] check the probably erroneous formula the F1 score in the official formula for partial matches 
- [x] adding argument to glue comp and fine label: https://github.com/impresso/CLEF-HIPE-2020-scorer/issues/1#issuecomment-580825787
- [x] sanity_check if provided labels are all available in gold standard
- [x] add system name as separate column extracting from filename
- [x] check how to make a union of two columns (or lists) to evaluate against gold standard
- [ ] implement slot error rate
    - also per type
    - compute F1/P/R

**Comment by mromanello** [comment]
can be closed
